Feature: TCOTA-513 - Assignments Tab
terracotta-education/terracotta pull request #325
Opened 2022-09-15 17:42 UTC by rmathis

2022-09-19 16:00 UTC, machristie requested changes
Thanks @rmathis. I've requested a few small changes in my review.

2022-09-19 18:59 UTC, rmathis commented on src/main/javascript/src/views/ExperimentAssignments.vue
> +
Fixed

2022-09-19 18:59 UTC, rmathis commented on src/main/javascript/src/views/ExperimentAssignments.vue
> +                          {{ item.assessmentDto.title }}
Fixed

2022-09-19 19:00 UTC, rmathis commented on src/main/javascript/src/views/ExperimentAssignments.vue
> +                <div class="d-block red--text mt-4">
Fixed

2022-09-19 19:00 UTC, rmathis commented on src/main/javascript/src/views/ExperimentAssignments.vue
> +    async exportData() {
Fixed

2022-09-19 19:00 UTC, rmathis commented on src/main/javascript/src/views/ExperimentAssignments.vue
> +    },
Fixed

2022-09-19 19:11 UTC, rmathis commented on src/main/javascript/src/views/ExperimentAssignments.vue
> +    }
Fixed

2022-09-20 16:39 UTC, machristie approved these changes
Looks good, thanks @rmathis

2022-09-20 16:39 UTC, merged